- name: Update Packages (Ubuntu)
  tags: ubuntu, update
  apt:
    update_cache: yes
    upgrade: yes
  when: ansible_distribution == "Ubuntu"

- name: Update Packages (Arch)
  tags: arch, update
  pacman:
    update_cache: yes
    upgrade: yes
  when: ansible_distribution == "Arch"


