- name: Update cache (Ubuntu)
  tags: setup, ubuntu
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install packages (Ubuntu)
  tags: setup, ubuntu
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - '{{ ubuntu_packages }}'
  when: ansible_distribution == "Ubuntu"

- name: Create Folders
  tags: setup, folders
  file:
    path: '{{item}}'
    mode: 0755
    recurse: yes
    state: directory
  with_items:
    - '{{default_dirs}}'

