- name: Workstation
  hosts: localhost
  tasks:
    - name: Update Packages (Ubuntu)
      tags: ubuntu, update
      apt:
        update_cache: yes
        upgrade: yes
      when: ansible_distribution == "Ubuntu"

    - name: Update Packages (Arch)
      tags: arch, update
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install nvm
      tags: install, nvm, nodejs
      shell:
        "curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash && source ~/.profile"

    - name: Install global npm Packages
      tags: init, setup, node
      npm:
        name: '{{item}}'
        global: yes
      with_items:
        - '{{node_gloabel_packages}}'

    - name: Install prettier
      tags: prettier, setup
      shell:
        "npm install -g --save-dev --save-exact prettier"

    - name: Install prettier-pug
      tags: pug, setup
      shell:
        "npm install -g --save-dev @prettier/plugin-pug"
