alias ..="cd .."
alias sWp="bash ~/.scripts/wpSelect.sh"
alias ll="lsd -l"
alias tmGet="bash ~/.scripts/tmGet.sh"
alias tmC="bash ~/.scripts/create_session.sh"
alias tmGet="bash ~/.scripts/get_session.sh"
