default_dirs:
  - ~/repos/github.com
  - ~/repos/gitlab.com
  - ~/repos/home_server
  - ~/repos/privat
  - ~/.newsboat
  - ~/.scripts

neovim_ppa: ppa:neovim-ppa/unstable
ubuntu_packages:
  - build-essential
  - cmake
  - pkg-config
  - libpthread-stubs0-dev
  - lua5.1
  - unzip
  - libtool
  - libtool-bin
  - gettext
  - tmux
  - curl
  - htop
  - lsof
  - ccache
  - ninja-build
  - golang
  - dconf-editor
  - moreutils
  - clangd
  - fzf
  - python3
  - python3-pip
  - python3-dev
  - python3-venv
  - ripgrep
  - software-properties-common
  - tldr
  - nodejs
  - pandoc

user_name: philmish
node_version: 14
